{{- if .Values.celeryBeat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relvy.fullname" . }}-celery-beat
  labels:
    {{- include "relvy.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-beat
spec:
  replicas: {{ .Values.celeryBeat.replicas }}
  selector:
    matchLabels:
      {{- include "relvy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      labels:
        {{- include "relvy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: celery-beat
        image: {{ include "relvy.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["sh", "-c"]
        args: ["celery -A make_celery beat --loglevel INFO"]
        env:
        - name: ENVIRONMENT
          value: {{ .Values.config.environment | quote }}
        - name: DB_HOST
          value: {{ .Values.database.endpoint	 | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_NAME
          value: {{ .Values.database.name | quote }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: password
        - name: REDIS_URL
          value: {{ include "relvy.redisUrl" . | quote }}
        - name: PYTHONPATH
          value: "/app"
        - name: SERVER_HOSTNAME
          value: {{ .Values.config.serverHostname | quote }}
        - name: RELVYAI_IMAGE_PULL_DOCKER_CONFIG_JSON
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.revyaiRegistry }}
              key: .dockerconfigjson
        - name: RELVYAI_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.license }}
              key: key
              optional: true
        - name: LANGFUSE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.langfuse }}
              key: public_key
              optional: true
        - name: LANGFUSE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.langfuse }}
              key: secret_key
              optional: true
        - name: LANGFUSE_HOST
          value: "http://langfuse-web.langfuse.svc.cluster.local:3000"
        - name: LANGFUSE_TRACING_ENVIRONMENT
          value: "production"
        - name: LANGFUSE_OBSERVE_DECORATOR_IO_CAPTURE_ENABLED
          value: "false"
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.github }}
              key: private_key
              optional: true
        - name: GITHUB_APP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.github }}
              key: client_id
              optional: true
        resources:
          {{- toYaml .Values.celeryBeat.resources | nindent 10 }}
{{- end }}
