{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relvy.fullname" . }}-celery
  labels:
    {{- include "relvy.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
      {{- include "relvy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        {{- include "relvy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: celery
        image: {{ include "relvy.image" . }}
        imagePullPolicy: {{ .Values.celery.image.pullPolicy }}
        command: ["sh", "-c"]
        args: ["celery -A make_celery worker --loglevel INFO --concurrency=4"]
        env:
        - name: ENVIRONMENT
          value: {{ .Values.config.environment | quote }}
        - name: DATABASE_URI
          value: {{ include "relvy.databaseUrl" . | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: password
        - name: POSTGRES_USER
          value: {{ .Values.database.external.user | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database.external.name | quote }}
        - name: POSTGRES_ENDPOINT
          value: {{ .Values.database.external.endpoint | quote }}
        - name: REDIS_URL
          value: {{ include "relvy.redisUrl" . | quote }}
        - name: PYTHONPATH
          value: "/app"
        - name: LLM_CLIENT
          value: {{ .Values.config.llmClient | quote }}
        - name: LLM_MODEL
          value: {{ .Values.config.llmModel | quote }}
        - name: HEAVY_LLM_CLIENT
          value: {{ .Values.config.heavyLlmClient | quote }}
        - name: HEAVY_LLM_MODEL
          value: {{ .Values.config.heavyLlmModel | quote }}
        - name: REASONING_LLM_CLIENT
          value: {{ .Values.config.reasoningLlmClient | quote }}
        - name: REASONING_LLM_MODEL
          value: {{ .Values.config.reasoningLlmModel | quote }}
        - name: SERVER_HOSTNAME
          value: {{ .Values.config.serverHostname | quote }}
        {{- if .Values.config.slack.enabled }}
        - name: SLACK_CLIENT_ID
          value: {{ .Values.config.slack.clientId | quote }}
        - name: SLACK_CLIENT_SECRET
          value: {{ .Values.config.slack.clientSecret | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.celery.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - celery
            - -A
            - make_celery
            - inspect
            - ping
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
{{- end }}