{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relvy.fullname" . }}-web
  labels:
    {{- include "relvy.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "relvy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "relvy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: web
        image: {{ include "relvy.image" . }}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        command: ["sh", "-c"]
        args: ["gunicorn --access-logfile - --error-logfile - --bind :{{ .Values.web.service.targetPort }} --workers 1 --threads 8 --timeout 0 'resolveml:create_app()'"]
        ports:
        - containerPort: {{ .Values.web.service.targetPort }}
          name: http
        env:
        - name: ENVIRONMENT
          value: {{ .Values.config.environment | quote }}
        - name: FLASK_SECRET_KEY
          value: {{ .Values.config.flaskSecretKey | quote }}
        - name: SERVER_HOSTNAME
          value: {{ .Values.config.serverHostname | quote }}
        - name: DATABASE_URI
          value: {{ include "relvy.databaseUrl" . | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: password
        - name: POSTGRES_USER
          value: {{ .Values.database.external.user | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database.external.name | quote }}
        - name: POSTGRES_ENDPOINT
          value: {{ .Values.database.external.endpoint | quote }}
        - name: REDIS_URL
          value: {{ include "relvy.redisUrl" . | quote }}
        - name: PYTHONPATH
          value: "/app"
        - name: LLM_CLIENT
          value: {{ .Values.config.llmClient | quote }}
        - name: LLM_MODEL
          value: {{ .Values.config.llmModel | quote }}
        - name: HEAVY_LLM_CLIENT
          value: {{ .Values.config.heavyLlmClient | quote }}
        - name: HEAVY_LLM_MODEL
          value: {{ .Values.config.heavyLlmModel | quote }}
        - name: REASONING_LLM_CLIENT
          value: {{ .Values.config.reasoningLlmClient | quote }}
        - name: REASONING_LLM_MODEL
          value: {{ .Values.config.reasoningLlmModel | quote }}
        - name: PORT
          value: {{ .Values.config.port | quote }}
        {{- if .Values.config.slack.enabled }}
        - name: SLACK_CLIENT_ID
          value: {{ .Values.config.slack.clientId | quote }}
        - name: SLACK_CLIENT_SECRET
          value: {{ .Values.config.slack.clientSecret | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
{{- end }}