apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "relvy.fullname" . }}-migration
  labels:
    {{- include "relvy.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "relvy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: {{ include "relvy.image" . }}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        command: ["sh", "-c"]
        args: ["flask --app=resolveml db upgrade"]
        env:
        - name: ENVIRONMENT
          value: {{ .Values.config.environment | quote }}
        - name: DB_HOST
          value: {{ .Values.database.endpoint	 | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_NAME
          value: {{ .Values.database.name | quote }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: password
        - name: REDIS_URL
          value: {{ include "relvy.redisUrl" . | quote }}
        - name: PYTHONPATH
          value: "/app"
        - name: SERVER_HOSTNAME
          value: {{ .Values.config.serverHostname | quote }}
        - name: LANGFUSE_TRACING_ENVIRONMENT
          value: "production"
